In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
X = np.array([["A"],["A"],["B"],["C"]])

In [4]:
X

array([['A'],
       ['A'],
       ['B'],
       ['C']], dtype='<U1')

In [5]:
encoder = OneHotEncoder(sparse=False)

In [6]:
encoder.fit_transform(X)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
encoder.categories_

[array(['A', 'B', 'C'], dtype='<U1')]

In [8]:
encoder2 = OneHotEncoder(sparse=False,drop="first")

In [9]:
encoder2.fit_transform(X)

array([[0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.]])

In [10]:
X2 = np.array([["A","Z"],["A","Y"],["B","Y"],["C","W"]])

In [11]:
X2

array([['A', 'Z'],
       ['A', 'Y'],
       ['B', 'Y'],
       ['C', 'W']], dtype='<U1')

In [12]:
encoder.fit_transform(X2)

array([[1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.]])

In [13]:
encoder.categories_

[array(['A', 'B', 'C'], dtype='<U1'), array(['W', 'Y', 'Z'], dtype='<U1')]

In [14]:
np.unique(X2[:,0])

array(['A', 'B', 'C'], dtype='<U1')

In [15]:
encoder3 = OneHotEncoder(sparse=False,categories=[np.unique(X2[:,0]),np.unique(X2[:,1])])

In [16]:
encoder3.fit_transform(X2)

array([[1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.]])

In [17]:
encoder4 = OneHotEncoder(categories=[np.unique(X2[:,0]),np.unique(X2[:,1])])
encoder4.fit_transform(X2)

<4x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [18]:
encoder4.fit_transform(X2).todense()

matrix([[1., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 0., 1., 1., 0., 0.]])