In [35]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv("sample_dataset.csv").iloc[:,0:5].dropna()

In [18]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness
2          19.69         21.25          130.00     1203.0          0.10960
3          11.42         20.38           77.58      386.1          0.14250
8          13.00         21.82           87.50      519.8          0.12730
13         15.85         23.95          103.70      782.7          0.08401
14         13.73         22.61           93.60      578.3          0.11310
..           ...           ...             ...        ...              ...
549        10.82         24.21           68.89      361.6          0.08192
550        10.86         21.48           68.51      360.5          0.07431
560        14.05         27.15           91.38      600.4          0.09929
564        21.56         22.39          142.00     1479.0          0.11100
567        20.60         29.33          140.10     1265.0          0.11780

[176 rows x 5 columns]

# Normalizzazione

Trasforma una variabile in un anuova variabile nell'intervallo [0,1]

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler = MinMaxScaler()

In [22]:
df_scaled = scaler.fit_transform(df)

In [23]:
df_scaled.min(0)

array([0., 0., 0., 0., 0.])

In [24]:
df_scaled.max(0)

array([1., 1., 1., 1., 1.])

In [25]:
df_scaled.std(0)

array([0.17887642, 0.15220992, 0.18095522, 0.15501694, 0.18344986])

# Standardizzazione

Trasforma una variabile affinché abbia media 0 e varianza 1

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scaler2 = StandardScaler()

In [28]:
df_scaled_2 = scaler2.fit_transform(df)

In [30]:
df_scaled_2.mean(0),df_scaled_2.std(0)

(array([-7.97341990e-16, -1.51394049e-16, -1.31208176e-16,  1.21115239e-16,
        -6.96412625e-16]),
 array([1., 1., 1., 1., 1.]))

# Scaler robusto

Pone la mediana uguale a 0 e il range interquartile uguale a 1

In [31]:
from sklearn.preprocessing import RobustScaler

In [32]:
scaler3 = RobustScaler()

In [33]:
df_scaled_3 = scaler3.fit_transform(df)

In [36]:
np.quantile(df_scaled_3,0.5,axis=0)

array([-1.65666092e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -3.47812057e-16])

In [37]:
np.quantile(df_scaled_3,0.75,axis=0)-np.quantile(df_scaled_3,0.25,axis=0)

array([1., 1., 1., 1., 1.])