In [1]:
import pandas as pd

In [14]:
import numpy as np

In [2]:
from sklearn.ensemble import RandomForestRegressor

In [3]:
from sklearn.feature_selection import SelectFromModel

In [5]:
df = pd.read_csv("sample_dataset.csv").iloc[:,0:10].dropna()

In [7]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [8]:
selector = SelectFromModel(RandomForestRegressor(), threshold="mean")

In [9]:
selector.fit_transform(X,y)

array([[0.1273 , 0.1932 ],
       [0.09831, 0.1027 ],
       [0.1075 , 0.127  ],
       [0.1024 , 0.06492],
       [0.1016 , 0.1255 ],
       [0.1041 , 0.1436 ],
       [0.0806 , 0.03789],
       [0.07721, 0.08751],
       [0.1122 , 0.1262 ],
       [0.1007 , 0.128  ],
       [0.1398 , 0.1765 ],
       [0.115  , 0.1807 ],
       [0.0943 , 0.09709],
       [0.1091 , 0.17   ],
       [0.09311, 0.05241],
       [0.09594, 0.05736],
       [0.09267, 0.04695],
       [0.08876, 0.09588],
       [0.1006 , 0.1146 ],
       [0.09812, 0.1298 ],
       [0.09345, 0.05991],
       [0.1008 , 0.1041 ],
       [0.08923, 0.05884],
       [0.07813, 0.0434 ],
       [0.09667, 0.08393],
       [0.08518, 0.04721],
       [0.115  , 0.1642 ],
       [0.08451, 0.1014 ],
       [0.09309, 0.05306],
       [0.08313, 0.04202],
       [0.09462, 0.09965],
       [0.1243 , 0.2364 ],
       [0.08302, 0.06374],
       [0.07517, 0.04726],
       [0.09996, 0.07542],
       [0.1167 , 0.2087 ],
       [0.1059 , 0.1147 ],
 

In [10]:
selector2 = SelectFromModel(RandomForestRegressor(), threshold="median")
selector2.fit_transform(X,y)

array([[1.300e+01, 5.198e+02, 1.273e-01, 1.932e-01, 2.350e-01],
       [1.981e+01, 1.260e+03, 9.831e-02, 1.027e-01, 1.582e-01],
       [1.308e+01, 5.200e+02, 1.075e-01, 1.270e-01, 1.967e-01],
       [9.504e+00, 2.739e+02, 1.024e-01, 6.492e-02, 1.815e-01],
       [1.348e+01, 5.592e+02, 1.016e-01, 1.255e-01, 1.720e-01],
       [1.328e+01, 5.452e+02, 1.041e-01, 1.436e-01, 1.974e-01],
       [1.305e+01, 5.272e+02, 8.060e-02, 3.789e-02, 1.819e-01],
       [9.173e+00, 2.609e+02, 7.721e-02, 8.751e-02, 2.341e-01],
       [1.268e+01, 4.990e+02, 1.122e-01, 1.262e-01, 1.905e-01],
       [1.380e+01, 5.841e+02, 1.007e-01, 1.280e-01, 1.662e-01],
       [1.311e+01, 5.302e+02, 1.398e-01, 1.765e-01, 1.925e-01],
       [1.510e+01, 6.745e+02, 1.150e-01, 1.807e-01, 2.001e-01],
       [1.845e+01, 1.075e+03, 9.430e-02, 9.709e-02, 1.692e-01],
       [1.180e+01, 4.320e+02, 1.091e-01, 1.700e-01, 2.678e-01],
       [1.206e+01, 4.486e+02, 9.311e-02, 5.241e-02, 1.590e-01],
       [1.080e+01, 3.576e+02, 9.594e-02,

In [13]:
selector3 = SelectFromModel(RandomForestRegressor(), threshold=0.1)
selector3.fit_transform(X,y)

array([[0.1273 , 0.1932 , 0.235  ],
       [0.09831, 0.1027 , 0.1582 ],
       [0.1075 , 0.127  , 0.1967 ],
       [0.1024 , 0.06492, 0.1815 ],
       [0.1016 , 0.1255 , 0.172  ],
       [0.1041 , 0.1436 , 0.1974 ],
       [0.0806 , 0.03789, 0.1819 ],
       [0.07721, 0.08751, 0.2341 ],
       [0.1122 , 0.1262 , 0.1905 ],
       [0.1007 , 0.128  , 0.1662 ],
       [0.1398 , 0.1765 , 0.1925 ],
       [0.115  , 0.1807 , 0.2001 ],
       [0.0943 , 0.09709, 0.1692 ],
       [0.1091 , 0.17   , 0.2678 ],
       [0.09311, 0.05241, 0.159  ],
       [0.09594, 0.05736, 0.1381 ],
       [0.09267, 0.04695, 0.1703 ],
       [0.08876, 0.09588, 0.1594 ],
       [0.1006 , 0.1146 , 0.1308 ],
       [0.09812, 0.1298 , 0.1809 ],
       [0.09345, 0.05991, 0.1834 ],
       [0.1008 , 0.1041 , 0.1813 ],
       [0.08923, 0.05884, 0.155  ],
       [0.07813, 0.0434 , 0.2101 ],
       [0.09667, 0.08393, 0.1638 ],
       [0.08518, 0.04721, 0.1449 ],
       [0.115  , 0.1642 , 0.1792 ],
       [0.08451, 0.1014 , 0.

In [15]:
selector4 = SelectFromModel(RandomForestRegressor(), threshold=-np.inf, max_features=3)
selector4.fit_transform(X,y)

array([[0.1273 , 0.1932 , 0.235  ],
       [0.09831, 0.1027 , 0.1582 ],
       [0.1075 , 0.127  , 0.1967 ],
       [0.1024 , 0.06492, 0.1815 ],
       [0.1016 , 0.1255 , 0.172  ],
       [0.1041 , 0.1436 , 0.1974 ],
       [0.0806 , 0.03789, 0.1819 ],
       [0.07721, 0.08751, 0.2341 ],
       [0.1122 , 0.1262 , 0.1905 ],
       [0.1007 , 0.128  , 0.1662 ],
       [0.1398 , 0.1765 , 0.1925 ],
       [0.115  , 0.1807 , 0.2001 ],
       [0.0943 , 0.09709, 0.1692 ],
       [0.1091 , 0.17   , 0.2678 ],
       [0.09311, 0.05241, 0.159  ],
       [0.09594, 0.05736, 0.1381 ],
       [0.09267, 0.04695, 0.1703 ],
       [0.08876, 0.09588, 0.1594 ],
       [0.1006 , 0.1146 , 0.1308 ],
       [0.09812, 0.1298 , 0.1809 ],
       [0.09345, 0.05991, 0.1834 ],
       [0.1008 , 0.1041 , 0.1813 ],
       [0.08923, 0.05884, 0.155  ],
       [0.07813, 0.0434 , 0.2101 ],
       [0.09667, 0.08393, 0.1638 ],
       [0.08518, 0.04721, 0.1449 ],
       [0.115  , 0.1642 , 0.1792 ],
       [0.08451, 0.1014 , 0.